plugins { id 'com.android.application' }

android {
    namespace 'app.forgepath.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'app.forgepath.mobile'
        minSdk 26
        targetSdk 35
        versionCode 5803
        versionName '5.8.0-beta'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
